#Day 1

Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included).The numbers obtained should be printed in a comma-separated sequence on a single line.

In [ ]:
n = range(2000, 3201)
for i in n:
  if i%7 == 0 and i%5 != 0:
    print(i, end = ",")
print("\b")

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199,

Write a program which can compute the factorial of a given numbers.The results should be printed in a comma-separated sequence on a single line.Suppose the following input is supplied to the program: 8 Then, the output should be:40320

In [ ]:
# using for loop
n = int(input())
a = 1
for i in range(n, 0, -1):
  a = a*i
print(a)

8
40320

In [ ]:
# using while loop
f = 1
n = int(input())
while n>=1:
  f = f*n
  n = n-1
print(f)

8
40320

#Day 2

Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.Suppose the following input is supplied to the program:
34,67,55,33,12,98
Then, the output should be:

['34', '67', '55', '33', '12', '98']
('34', '67', '55', '33', '12', '98')

In [ ]:
lst = input().split(',')  
tpl = tuple(lst)
print(lst)
print(tpl)

34,35
['34', '35']
('34', '35')

Define a class which has at least two methods:

getString: to get a string from console input
printString: to print the string in upper case.
Also please include simple test function to test the class methods.

In [ ]:
class IOstring():
    def get_string(self):
        self.s = input()

    def print_string(self):
        print(self.s.upper())

xx = IOstring()
xx.get_string()
xx.print_string()

raw
RAW

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 _ C _ D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.For example Let us assume the following comma separated input sequence is given to the program:

In [ ]:
from math import sqrt
C,H = 50,30

def calc(D):
    return sqrt((2*C*D)/H)

print(",".join([str(int(calc(int(i)))) for i in input().split(',')]))

5
4

_Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i _ j.*

Note: i=0,1.., X-1; j=0,1,¡­Y-1. Suppose the following inputs are given to the program: 3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [ ]:
x,y = map(int,input().split(','))
lst = []

for i in range(x):
    tmp = []
    for j in range(y):
        tmp.append(i*j)
    lst.append(tmp)

print(lst)

5,4
[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6], [0, 3, 6, 9], [0, 4, 8, 12]]

Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world
Then, the output should be:

bag,hello,without,world

In [ ]:
lst = input().split(',')
lst.sort()
print(",".join(lst))

without,hello,bag,world
bag,hello,without,world

Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.

Suppose the following input is supplied to the program:

Hello world
Practice makes perfect
Then, the output should be:

HELLO WORLD
PRACTICE MAKES PERFECT

In [ ]:
lst = []

while True:
    x = input()
    if len(x)==0:
        break
    lst.append(x.upper())

for line in lst:
    print(line)

#Day 3

Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again
Then, the output should be:

again and hello makes perfect practice world

In [ ]:
a = input().split(' ')
s = list(set(a))
s.sort()
print(' '.join(s))

hello world and practice makes perfect and hello world again
again and hello makes perfect practice world

Or

In [ ]:
word = input().split()

for i in word:
    if word.count(i) > 1:    #count function returns total repeatation of an element that is send as argument
        word.remove(i)     # removes exactly one element per call

word.sort()
print(" ".join(word))

hello world and practice makes perfect and hello world again
again and hello makes perfect practice world

Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.

Example:

0100,0011,1010,1001
Then the output should be:

1010
Notes: Assume the data is input by console.

In [ ]:
a = input().split(',')
for i in a:
  if int(i, 2)%5 == 0:
    print(i)

0100,0011,1010,1001
1010

Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.The numbers obtained should be printed in a comma-separated sequence on a single line.

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

In [ ]:
# for i in range(1000, 3001):
#   if i%2 == 0:
#     print(str(i))
lst = []
for i in range(1000, 3001):
  clk = 1
  for j in str(i):
    if ord(j)%2 != 0:
      clk = 0
  if clk == 1:
    lst.append(str(i))
print(','.join(lst))

2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888

In [ ]:
lst = []

for i in range(1000,3001):
    flag = 1
    for j in str(i):          # every integer number i is converted into string
        if ord(j)%2 != 0:     # ord returns ASCII value and j is every digit of i
            flag = 0          # flag becomes zero if any odd digit found
    if flag == 1:
        lst.append(str(i))    # i is stored in list as string

print(",".join(lst))

2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888

Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123
Then, the output should be:

LETTERS 10
DIGITS 3

In [ ]:
a = input()
di = 0
le = 0
for i in a:
  if i.isdigit():
    di += 1
  elif i.isalpha():
    le += 1
print(di, le)

hello world! 123
3 10

#Day 4

Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.

Suppose the following input is supplied to the program:

Hello world!
Then, the output should be:

UPPER CASE 1
LOWER CASE 9

In [ ]:
n = input()
uc = 0
lc = 0
for i in n:
  if i.isupper():
    uc += 1
  if i.islower():
    lc += 1
print(uc, lc)

Hello world
1 9

Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.

Suppose the following input is supplied to the program:

9
Then, the output should be:

11106

In [ ]:
a = input()
s = 0
e = ''
for i in range(4):
  e+=a
  s = s+int(e)
print(s)

9
11106

#Day 5

Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers. >Suppose the following input is supplied to the program:

1,2,3,4,5,6,7,8,9
Then, the output should be:

1,9,25,49,81

In [ ]:
ia = input().split(',')
al = [int(i) for i in ia]
def odd_sq(num):
    if num%2 != 0:
        return num
mf = [str(i*i) for i in filter(odd_sq, al)]
print(','.join(mf))

1,2,3,4,5,6,7,8,9
1,9,25,49,81

Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following:

D 100
W 200
D means deposit while W means withdrawal.
Suppose the following input is supplied to the program:

D 300
D 300
W 200
D 100
Then, the output should be:

500

In [ ]:
total = 0
while True:
  a = input().split()
  if not a:
    break
  cm, num = map(str,a) # also use filter instead of map
  if cm == 'w' or cm == 'W':
    total -= int(num)
  if cm == 'd' or cm == 'D':
    total += int(num)
print(total)

d 200
w 100

100

In [ ]:
a = [1,2,3,4,5]
b,c,d,e,f = filter(int, a)
print(b)

1

#Day 6

A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:

At least 1 letter between [a-z]
At least 1 number between [0-9]
At least 1 letter between [A-Z]
At least 1 character from [$#@]
Minimum length of transaction password: 6
Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:

ABd1234@1

You are required to write a program to sort the (name, age, score) tuples by ascending order where name is string, age and score are numbers. The tuples are input by console. The sort criteria is:

1: Sort based on name
2: Then sort based on age
3: Then sort by score
The priority is that name > age > score.

If the following tuples are given as input to the program:

Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85
Then, the output of the program should be:

[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]

In [ ]:
li = []
while True:
  a = input().split(',')
  if not a[0]:
    break
  li.append(tuple(a))
li.sort(key = lambda x: (x[0], int(x[1]), int(x[2])))
print(li)

Tom,19,80
John,20,90

[('John', '20', '90'), ('Tom', '19', '80')]

#Day 7

Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

Suppose the following input is supplied to the program:

7
Then, the output should be:

0
7
14

In [ ]:
class div_bysev():
  def __init__(self):
    self.n = int(input())
  def div(self):
    for i in range(0, self.n+1):
      if i%7 == 0:
        yield i
g = div_bysev()
s = g.div()
for i in s:
  print(i)

7
0
7

In [ ]:
class Divisible:

    def by_seven(self, n):
        for number in range(1,n + 1):
            if number % 7 == 0: yield number


divisible = Divisible()
generator = divisible.by_seven(int(input("Please insert a number. --> ")))
for number in generator:
    print(number)

Please insert a number. --> 7
7

#Day 8

Write a program to compute the frequency of the words from the input. The output should output after sorting the key alphanumerically.

Suppose the following input is supplied to the program:

New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
Then, the output should be:

2:2
3.:1
3?:1
New:1
Python:5
Read:1
and:1
between:1
choosing:1
or:2
to:1

In [ ]:
n = input().split()
d = {}
for i in n:
   d[i] = n.count(i)
d = sorted(d.items())
for i in d:
  print(i[0], ':' ,i[1], end = ' ')

New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
2 : 2 3. : 1 3? : 1 New : 1 Python : 5 Read : 1 and : 1 between : 1 choosing : 1 or : 2 to : 1

Write a method which can calculate square value of number

Hints:
Using the ** operator which can be written as n**p where means n^p

In [ ]:
class square():
  def __init__(self):
    self.n = int(input())
  def show(self):
    print(self.n**2)

s = square()
s.show()

9
81

Python has many built-in functions, and if you do not know how to use it, you can read document online or find some books. But Python has a built-in document function for every built-in functions.

Please write a program to print some Python built-in functions documents, such as abs(), int(), raw_input()

And add document for your own function

Hints:
The built-in document method is __doc__

In [ ]:
print(abs.__doc__)
print(list.__doc__)


def sq(n):
  '''
  square of number
  '''
  return n**2

print(sq.__doc__)

Return the absolute value of the argument.
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

  square of number

Define a class, which have a class parameter and have a same instance parameter.

Hints:
Define an instance parameter, need add it in __init__ method.You can init an object with construct parameter or set the value later

In [ ]:
class car:
  name = 'Maruti'
  def __init__(self, name = None):
    self.name = name
  def show(self):
    print(self.name)

toyota = car('Toyota')
# print(car.name, toyota.name)
toyota.show()

Toyota
Toyota

#Day 9

Define a function which can compute the sum of two numbers.

Hints:
Define a function with two numbers as arguments. You can compute the sum in the function and return the value.

In [ ]:
def add(i, j):
  return i+j
add(1,2)

3

In [ ]:
# using lambda

a = lambda x, y: x+y 
a(1, 2)

3

Define a function that can convert a integer into a string and print it in console.

Hints:
Use str() to convert a number to string.

In [ ]:
i = int(input())
def convert_str(n):
  return str(n)
convert_str(i)

1

'1'

In [ ]:
# Using lambda
conv = lambda x: str(x)
conv(1)

'1'

Define a function that can receive two integer numbers in string form and compute their sum and then print it in console.

Hints:
Use int() to convert a string to integer.

In [ ]:
def sum_int(a, b):
  c = int(a)+int(b)
  return c

a = '1'
b = '2'
sum_int(a, b)

3

Define a function that can accept two strings as input and concatenate them and then print it in console.

Hints:
Use + sign to concatenate the strings.

In [ ]:
conc = lambda a, b: a + b
conc('1', '2')

'12'

Define a function that can accept two strings as input and print the string with maximum length in console. If two strings have the same length, then the function should print all strings line by line.

Hints:
Use len() function to get the length of a string.

In [ ]:
def len_str(a, b):
  if len(a) > len(b):
    print(a)
  elif len(b) > len(a):
    print(b)
  else:
    print(a)
    print(b)


len_str('asdad', 'abcaa')

asdad
abcaa

#Day 10

Define a function which can print a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys.

Hints:
Use dict[key]=value pattern to put entry into a dictionary.Use ** operator to get power of a number.Use range() for loops.

In [ ]:
def dict(n):
  d = {}
  for i in range(1, n+1):
    d[i] = i**2
  return d

dict(20)

{1: 1,
 2: 4,
 3: 9,
 4: 16,
 5: 25,
 6: 36,
 7: 49,
 8: 64,
 9: 81,
 10: 100,
 11: 121,
 12: 144,
 13: 169,
 14: 196,
 15: 225,
 16: 256,
 17: 289,
 18: 324,
 19: 361,
 20: 400}

In [ ]:
# dictionary comp
def dict():
  d = {i: i**2 for i in range(1, 21)}
  return d
dict()

{1: 1,
 2: 4,
 3: 9,
 4: 16,
 5: 25,
 6: 36,
 7: 49,
 8: 64,
 9: 81,
 10: 100,
 11: 121,
 12: 144,
 13: 169,
 14: 196,
 15: 225,
 16: 256,
 17: 289,
 18: 324,
 19: 361,
 20: 400}

Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the keys only.

Hints:
Use dict[key]=value pattern to put entry into a dictionary.Use ** operator to get power of a number.Use range() for loops.Use keys() to i

In [ ]:
def dict(n):
  d = {}
  for i in range(1, n+1):
    d[i] = i**2
  for i in d.keys():
    print(i)
dict(20)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

Define a function which can generate and print a list where the values are square of numbers between 1 and 20 (both included).

Hints:
Use ** operator to get power of a number.Use range() for loops.Use list.append() to add values into a list.

In [ ]:
def list_sq(n):
  l = []
  for i in range(1, n+1):
    l.append(i**2)
  return l
list_sq(20)

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400]

In [ ]:
def list_sq(n):
  l = [i**2 for i in range(1, n+1)]
  return l
list_sq(20)

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400]

Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print the first 5 elements in the list.

Hints:
Use ** operator to get power of a number.Use range() for loops.Use list.append() to add values into a list.Use [n1:n2] to slice a list

In [ ]:
def lis():
  l = [i**2 for i in range(1, 21)]
  return l[:5]
lis()

[1, 4, 9, 16, 25]

Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print all values except the first 5 elements in the list.

Hints: Use ** operator to get power of a number.Use range() for loops.Use list.append() to add values into a list.Use [n1:n2] to slice a

In [ ]:
def lis():
  l = [i**2 for i in range(1, 21)]
  return l[5:]
lis()

[36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]

Define a function which can generate and print a tuple where the value are square of numbers between 1 and 20 (both included).

Hints:
Use ** operator to get power of a number.Use range() for loops.Use list.append() to add values into a list.Use tuple() to get a tuple from a list

In [ ]:
def lis():
  l = [i**2 for i in range(1, 21)]
  return tuple(l)
lis()

(1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400)

#Day 11

With a given tuple (1,2,3,4,5,6,7,8,9,10), write a program to print the first half values in one line and the last half values in one line.

Hints:
Use [n1:n2] notation to get a slice from a tuple.

In [ ]:
t = (1,2,3,4,5,6,7,8,9,10)
print(t[:5])
print(t[5:])

(1, 2, 3, 4, 5)
(6, 7, 8, 9, 10)

In [ ]:
t = (1,2,3,4,5,6,7,8,9,10)
l = int(len(t)/2)
print(t[:l])
print(t[l:])

(1, 2, 3, 4, 5)
(6, 7, 8, 9, 10)

Write a program to generate and print another tuple whose values are even numbers in the given tuple (1,2,3,4,5,6,7,8,9,10).

Hints:
Use "for" to iterate the tuple. Use tuple() to generate a tuple from a list.

In [ ]:
def even():
  li = []
  t = (1,2,3,4,5,6,7,8,9,10)
  for i in t:
    if i % 2 == 0:
      li.append(i)
  return tuple(li)
even()

(2, 4, 6, 8, 10)

Write a program which accepts a string as input to print "Yes" if the string is "yes" or "YES" or "Yes", otherwise print "No".

Hints:
Use if statement to judge condition.

In [ ]:
n = input()
if n == 'Yes' or n == 'YES' or n == 'yes':
  print('Yes')
else:
  print('No')

yes
Yes

Write a program which can map() to make a list whose elements are square of elements in [1,2,3,4,5,6,7,8,9,10].

Hints:
Use map() to generate a list.Use lambda to define anonymous functions.

In [ ]:
l = [1,2,3,4,5,6,7,8,9,10]
print(list(map(lambda x: x**2, l)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Write a program which can map() and filter() to make a list whose elements are square of even number in [1,2,3,4,5,6,7,8,9,10].

Hints:
Use map() to generate a list.Use filter() to filter elements of a list.Use lambda to define anonymous functions.

In [ ]:
l = [1,2,3,4,5,6,7,8,9,10]
fl = lambda x: x%2 == 0
mp = lambda x: x**2
print(list(map(mp, filter(fl, l))))

[4, 16, 36, 64, 100]

Write a program which can filter() to make a list whose elements are even number between 1 and 20 (both included).

Hints:
Use filter() to filter elements of a list.Use lambda to define anonymous functions.

In [ ]:
l = [i for i in range(1, 21)]
print(list(filter(lambda x: x%2 == 0, l)))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

#Day 12

Write a program which can map() to make a list whose elements are square of numbers between 1 and 20 (both included).

Hints:
Use map() to generate a list. Use lambda to define anonymous functions.

In [ ]:
l = [i for i in range(1, 21)]
print(list(map(lambda x: x**2, l)))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]

Define a class named American which has a static method called printNationality.

Hints:
Use @staticmethod decorator to define class static method.There are also two more methods.To know more, go to this link.

In [ ]:
class American:
  @staticmethod
  def printNationality():
    print("American")

nationality = American()
nationality.printNationality()

American

Define a class named American and its subclass NewYorker.

Hints:
Use class Subclass(ParentClass) to define a subclass.*

In [ ]:
class American:
  def __init__(self):
    self.name = 'Mohit'
class NewYorker(American):
  def printName(self):
    super().__init__()
    print(self.name)

name = NewYorker()
name.printName()

Mohit

#Day 13

Define a class named Circle which can be constructed by a radius. The Circle class has a method which can compute the area.

Hints
Use def methodName(self) to define a method.

In [ ]:
class Circle():
  def __init__(self):
    self.r = int(input('Radius: '))
  def area(self):
    self.a = 3.14*self.r**2
  def showArea(self):
    print(self.a)

area = Circle()
area.area()
area.showArea()

Radius: 5
78.5

Define a class named Rectangle which can be constructed by a length and width. The Rectangle class has a method which can compute the area.

Hints
Use def methodName(self) to define a method.

In [ ]:
class Rectangle():
  def __init__(self, l, w):
    self.len = l
    self.wid = w
  def findArea(self):
    self.area = self.len*self.wid
  def show(self):
    print(self.area)

a = Rectangle(3, 4)
a.findArea()
a.show()

12

Define a class named Shape and its subclass Square. The Square class has an init function which takes a length as argument. Both classes have a area function which can print the area of the shape where Shape's area is 0 by default.

Hints
To override a method in super class, we can define a method with the same name in the super class.

In [ ]:
class Shape:
  def area(self):
    return 0

class Square(Shape):
  def __init__(self, length = 0):
    super().area()
    self.length = length
  def area(self):
    return self.length**2
    
s = Square(5)
# Square().area()
s.area()

25

Please raise a RuntimeError exception.

Hints
UUse raise() to raise an exception.

In [ ]:
# try:
#   n = int(input())
# except Exception as e:
#   print(e)

raise RuntimeError('something wrong')

RuntimeError: ignored

#Day 14

Write a function to compute 5/0 and use try/except to catch the exceptions.

Hints
Use try/except to catch exceptions.

In [ ]:
def divide():
  try:
    a,b = 5,0
    c = a/b
    return c
  # except ZeroDivisionError as e:
  #   print(e)
  except Exception as e:
    print(e)
divide()

division by zero

Define a custom exception class which takes a string message as attribute.

Hints
To define a custom exception, we need to define a class inherited from Exception.

In [ ]:
class CustomError(Exception):
  def __init__(self, err):
    self.err = err

n=1

if n < 10: 
  raise CustomError('new to programming')
else:
  raise CustomError('Too old to Programming')

CustomError: ignored

Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the user name of a given email address. Both user names and company names are composed of letters only.

Example: If the following email address is given as input to the program:

john@google.com
Then, the output of the program should be:

john
In case of input data being supplied to the question, it should be assumed to be a console input.

Hints
Use \w to match letters.

In [ ]:
email = 'john@google.com'
email = email.split('@')
email[0]

'john'

#Day 15

Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the company name of a given email address. Both user names and company names are composed of letters only.

Example: If the following email address is given as input to the program:

john@google.com
Then, the output of the program should be:

google
In case of input data being supplied to the question, it should be assumed to be a console input.

In [90]:
import re
email = "john@google.com elise@python.com"
ans = re.findall('@(\w+)', email)
print(ans)

['google', 'python']

Write a program which accepts a sequence of words separated by whitespace as input to print the words composed of digits only.

Example: If the following words is given as input to the program:

2 cats and 3 dogs.
Then, the output of the program should be:

['2', '3']
In case of input data being supplied to the question, it should be assumed to be a console input.

Hints
Use re.findall() to find all substring using regex.

In [91]:
st = '2 cats and 3 dogs'
# re.findall('[0-9]', str)
re.findall('\d+', st)

['2', '3']

Print a unicode string "hello world".

Hints
Use u'strings' format to define unicode string.

In [92]:
st = u'hello world'
print(st)

hello world

Write a program to read an ASCII string and to convert it to a unicode string encoded by utf-8.

Hints
Use unicode()/encode() function to convert.

In [93]:
# str = 'hello world'
# print(str.encode('utf-8'))

s = input()
u = s.encode('utf-8')
print(u)

9
b'9'

Write a special comment to indicate a Python source code file is in unicode.

Hints
Use unicode() function to convert.

In [37]:
# comment

Write a program to compute 1/2+2/3+3/4+...+n/n+1 with a given n input by console (n>0).

Example: If the following n is given as input to the program:

5
Then, the output of the program should be:

3.55
In case of input data being supplied to the question, it should be assumed to be a console input.

Hints
Use float() to convert an integer to a float.Even if not converted it wont cause a problem because python by default understands the data type of a value

In [47]:
n = int(input())
d = 0
for i in range(1, n+1):
  d = d+ i/(i+1)
print('%.2f'%d)

5
3.55

#Day 16

Write a program to compute:

f(n)=f(n-1)+100 when n>0
and f(0)=0
with a given n input by console (n>0).

Example: If the following n is given as input to the program:

5
Then, the output of the program should be:

500
In case of input data being supplied to the question, it should be assumed to be a console input.

Hints
We can define recursive function in Python.

In [48]:
def f(n):
  if n == 0:
    return 0
  return f(n-1)+100
f(5)

500

The Fibonacci Sequence is computed based on the following formula:

f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program to compute the value of f(n) with a given n input by console.

Example: If the following n is given as input to the program:

7
Then, the output of the program should be:

13
In case of input data being supplied to the question, it should be assumed to be a console input.

Hints
We can define recursive function in Python.

In [56]:
a = 0
b = 1

# i = 7
for i in range(7):
  c = a+b
  a = b
  b = c
print(a)

13

In [59]:
def f(n):
  if n<2:
    return n
  return f(n-1)+f(n-2)
f(7)

13

The Fibonacci Sequence is computed based on the following formula:

f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program to compute the value of f(n) with a given n input by console.

Example: If the following n is given as input to the program:

7
Then, the output of the program should be:

0,1,1,2,3,5,8,13
In case of input data being supplied to the question, it should be assumed to be a console input.

Hints
We can define recursive function in Python. Use list comprehension to generate a list from an existing list. Use string.join() to join a list of strings.

In [67]:
a = 0
b = 1
n = 7
for i in range(n+1):
  print(a)
  c = a+b
  a = b
  b = c

0
1
1
2
3
5
8
13

Please write a program using generator to print the even numbers between 0 and n in comma separated form while n is input by console.

Example: If the following n is given as input to the program:

10
Then, the output of the program should be:

0,2,4,6,8,10
In case of input data being supplied to the question, it should be assumed to be a console input.

Hints
Use yield to produce the next value in generator.

In [88]:
def f(n):
  for i in range(0, n+1):
    if i%2 == 0:
      yield i

lst = []
for i in f(10):
  lst.append(i)

[0, 2, 4, 6, 8, 10]